/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Bale = IDL.Record({
  'id' : IDL.Nat,
  'description' : IDL.Text,
  'isAngry' : IDL.Bool,
});

export const idlService = IDL.Service({
  'addBale' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'angryBaleCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getAllBales' : IDL.Func([], [IDL.Vec(Bale)], ['query']),
  'getBale' : IDL.Func([IDL.Nat], [IDL.Opt(Bale)], ['query']),
  'toggleAngry' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Bale = IDL.Record({
    'id' : IDL.Nat,
    'description' : IDL.Text,
    'isAngry' : IDL.Bool,
  });
  
  return IDL.Service({
    'addBale' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'angryBaleCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getAllBales' : IDL.Func([], [IDL.Vec(Bale)], ['query']),
    'getBale' : IDL.Func([IDL.Nat], [IDL.Opt(Bale)], ['query']),
    'toggleAngry' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };